name: Run
on: [push]

jobs:
  build-latest:
    name: Run
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Run
        run: ./run.sh
